crunchyroll:
  email: "<user-email>"
  password: "<user-password>"
mega:
  email: "<mega-email>"
  password: "<mega-password>"
google:
  service_account_json: "crunchyroll-bot-a5c08043bc5c.json"
voice:
  enabled: true
openai:
  api_key: ""
